# ✅ NumPy Practice Notebook – Answer Key

This notebook provides the answers to the NumPy exercises covering:
- Creating arrays
- Indexing
- Scalar, row, and column broadcasting
- Performance comparison

## 1️⃣ Create a 2D Array

In [1]:
import numpy as np

# Create a 3x3 array with numbers 1 to 9
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("📐 3D Array:\n", matrix)

StatementMeta(, 30e000f1-9dad-4194-9e6a-21ce239e5a38, 3, Finished, Available, Finished)

📐 3D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## 2️⃣ Indexing

In [2]:
print("First row:", matrix[0])
print("Item at (2, 3):", matrix[1, 2])
print("Sub-matrix:\n", matrix[0:2, 0:2])

StatementMeta(, 30e000f1-9dad-4194-9e6a-21ce239e5a38, 4, Finished, Available, Finished)

First row: [1 2 3]
Item at (2, 3): 6
Sub-matrix:
 [[1 2]
 [4 5]]


## 3️⃣ Scalar Broadcasting

In [3]:
print("Add 5:\n", matrix + 5)
print("Multiply by 3:\n", matrix * 3)

StatementMeta(, 30e000f1-9dad-4194-9e6a-21ce239e5a38, 5, Finished, Available, Finished)

Add 5:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
Multiply by 3:
 [[ 3  6  9]
 [12 15 18]
 [21 24 27]]


## 4️⃣ Row-wise Broadcasting

In [4]:
row_add = np.array([1, 0, -1])
print("Row-wise add:\n", matrix + row_add)

StatementMeta(, 30e000f1-9dad-4194-9e6a-21ce239e5a38, 6, Finished, Available, Finished)

Row-wise add:
 [[2 2 2]
 [5 5 5]
 [8 8 8]]


## 5️⃣ Column-wise Broadcasting

In [5]:
col_add = np.array([10, 20, 30]).reshape(3, 1)
print("Column-wise add:\n", matrix + col_add)

StatementMeta(, 30e000f1-9dad-4194-9e6a-21ce239e5a38, 7, Finished, Available, Finished)

Column-wise add:
 [[11 12 13]
 [24 25 26]
 [37 38 39]]


## 6️⃣ Performance: Python List vs NumPy

In [6]:
import time

numbers = list(range(1_000_000))
start = time.time()
doubled_list = [n * 2 for n in numbers]
end = time.time()
print(f"⏳ Python list time: {end - start:.6f} seconds")

np_array = np.array(numbers)
start = time.time()
doubled_np = np_array * 2
end = time.time()
print(f"⚡ NumPy time: {end - start:.6f} seconds")

StatementMeta(, 30e000f1-9dad-4194-9e6a-21ce239e5a38, 8, Finished, Available, Finished)

⏳ Python list time: 0.036908 seconds
⚡ NumPy time: 0.002141 seconds
